"""
test_routing_table_validation.py: stdlib unittest boundary suite for
routing-table-validation.py (opt-in PreToolUse hook).

Run:  python hooks/disabled/test_routing_table_validation.py
Pass: all tests exit 0, no crash.

Strategy: each test launches the hook as a subprocess, feeds a JSON payload
on stdin, captures stdout, and asserts deny vs allow.

  DENY  -> stdout contains permissionDecision:deny
  ALLOW -> stdout is empty (or whitespace only)
"""

import io
import json
import os
import subprocess
import sys
import unittest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "routing-table-validation.py")
_PYTHON = sys.executable

# Repo root: two levels up from disabled/ (disabled/ -> hooks/ -> repo root)
_REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
# Registry lives at <repo>/.claude/registry.json (generated by scripts/generate_registry.py)
_REGISTRY = os.path.join(_REPO, ".claude", "registry.json")


def _run_hook(payload: dict) -> tuple[str, int]:
    """Run the hook subprocess, return (stdout, returncode)."""
    result = subprocess.run(
        [_PYTHON, _HOOK],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result.stdout, result.returncode


def _skill_path(name: str = "process-qa") -> str:
    """Return a plausible SKILL.md path for the given skill name."""
    return os.path.join(_REPO, ".claude", "skills", name, "SKILL.md").replace("\\", "/")


def _claude_md_path() -> str:
    return os.path.join(_REPO, "CLAUDE.md").replace("\\", "/")


def _non_routing_path() -> str:
    return os.path.join(_REPO, "work", "note.md").replace("\\", "/")


def _is_deny(stdout: str) -> bool:
    if not stdout.strip():
        return False
    try:
        obj = json.loads(stdout.strip())
        return (
            obj.get("hookSpecificOutput", {}).get("permissionDecision") == "deny"
        )
    except Exception:
        return False


def _is_allow(stdout: str) -> bool:
    return not stdout.strip()


def _deny_names(stdout: str) -> list[str]:
    """Extract the agent names mentioned in the deny reason, for targeted assertions."""
    try:
        obj = json.loads(stdout.strip())
        reason = obj.get("hookSpecificOutput", {}).get("permissionDecisionReason", "")
        import re
        return re.findall(r'"([a-z][a-z0-9_-]+)"', reason)
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Load a real agent from registry for ALLOW tests
# ---------------------------------------------------------------------------

def _real_agent_from_registry() -> str:
    """Return one agent name guaranteed to be in registry.json."""
    try:
        with open(_REGISTRY, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        agents = data.get("agents", {})
        if isinstance(agents, dict):
            # prefer a kebab-named one for shape clarity
            for name in agents:
                if "-" in name and name == name.lower():
                    return name.lower()
            return list(agents.keys())[0].lower()
    except Exception:
        pass
    return "architect-reviewer"  # known present


_REAL_AGENT = _real_agent_from_registry()


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

class TestDenyCases(unittest.TestCase):
    """Cases that MUST produce permissionDecision:deny."""

    def test_edit_skill_md_must_dispatch_ghost_agent(self):
        """
        Edit to SKILL.md adding MUST DISPATCH line with a nonexistent agent.
        Expected: DENY naming 'nonexistent-agent'.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _skill_path("process-qa"),
                "old_string": "OLD_CONTENT",
                "new_string": "MUST DISPATCH: process-qa, nonexistent-agent, pm",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0, "Hook must always exit 0")
        self.assertTrue(_is_deny(stdout), f"Expected DENY, got: {stdout!r}")
        self.assertIn("nonexistent-agent", _deny_names(stdout),
                      f"Deny reason must name 'nonexistent-agent'; got: {stdout!r}")

    def test_edit_skill_md_routing_table_row_ghost(self):
        """
        Edit to SKILL.md adding a routing-table row with an unresolved ghost agent.
        Expected: DENY naming 'renamed-ghost-agent'.
        """
        # Provide table context in the new_string itself
        new_string = (
            "| Agent dispatch | routing |\n"
            "| ------- | ------- |\n"
            "| Some domain | renamed-ghost-agent | trigger |\n"
        )
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _skill_path("process-build"),
                "old_string": "OLD",
                "new_string": new_string,
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_deny(stdout), f"Expected DENY, got: {stdout!r}")
        self.assertIn("renamed-ghost-agent", _deny_names(stdout),
                      f"Deny reason must name 'renamed-ghost-agent'; got: {stdout!r}")

    def test_write_skill_md_subagent_type_ghost(self):
        """
        Write of a SKILL.md whose content contains subagent_type: "ghost-reviewer".
        Expected: DENY naming 'ghost-reviewer'.
        """
        content = (
            "---\n"
            "name: example-skill\n"
            "---\n"
            "\n"
            "## Dispatch\n"
            'subagent_type: "ghost-reviewer"\n'
            "\n"
            "Do the thing.\n"
        )
        payload = {
            "tool_name": "Write",
            "tool_input": {
                "file_path": _skill_path("example-skill"),
                "content": content,
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_deny(stdout), f"Expected DENY, got: {stdout!r}")
        self.assertIn("ghost-reviewer", _deny_names(stdout),
                      f"Deny reason must name 'ghost-reviewer'; got: {stdout!r}")


class TestAllowCases(unittest.TestCase):
    """Cases that MUST produce ALLOW (silent stdout): false-positive guards."""

    def test_allow_all_real_agents_in_must_dispatch(self):
        """
        MUST DISPATCH with only real agents (both loaded dynamically from registry.json).
        Expected: ALLOW.
        """
        # Use _REAL_AGENT twice to guarantee both tokens resolve: no hardcoded names
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _skill_path("process-build"),
                "old_string": "OLD",
                "new_string": f"MUST DISPATCH: {_REAL_AGENT}",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout), f"Expected ALLOW (silent), got: {stdout!r}")

    def test_allow_real_agent_from_registry(self):
        """
        Edit adding a MUST DISPATCH referencing an agent actually in registry.json.
        Expected: ALLOW.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": f"MUST DISPATCH: {_REAL_AGENT}",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW for real agent '{_REAL_AGENT}', got: {stdout!r}")

    def test_allow_ghost_in_prose_not_dispatch_position(self):
        """
        Ghost name in free prose (no dispatch keyword) inside CLAUDE.md.
        Expected: ALLOW (not a dispatch-position line).
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "We used to call it old-orchestrator-thing but that is retired.",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout), f"Expected ALLOW (prose, not dispatch pos), got: {stdout!r}")

    def test_allow_ghost_inside_fenced_code_block(self):
        """
        Ghost name inside a fenced code block.
        Expected: ALLOW (code blocks are excluded from dispatch-position scanning).
        """
        new_string = (
            "Here is an example:\n"
            "```\n"
            "MUST DISPATCH: ghost-code-agent\n"
            "```\n"
            "End of example.\n"
        )
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": new_string,
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (inside fenced block), got: {stdout!r}")

    def test_allow_non_routing_file_with_ghost_must_dispatch(self):
        """
        Ghost name in a MUST DISPATCH line but in a non-routing file.
        Expected: ALLOW (gate a fails: wrong file class).
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _non_routing_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: totally-ghost-agent",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (non-routing file), got: {stdout!r}")

    def test_allow_single_word_token_not_agent_shaped(self):
        """
        Single-word token (no hyphen/underscore: not agent-shaped by shape gate).
        Expected: ALLOW (gate c fails: shape mismatch).
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: orchestrator",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (single-word, fails shape gate), got: {stdout!r}")

    def test_allow_capitalized_token_not_agent_shaped(self):
        """
        Capitalized word in a MUST DISPATCH line: not agent-shaped (starts uppercase).
        Expected: ALLOW (gate c fails).
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: SomeAgent",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (Capitalized, fails shape gate), got: {stdout!r}")

    def test_allow_path_shaped_token_not_agent_shaped(self):
        """
        Path-like token in a MUST DISPATCH line.
        Expected: ALLOW (gate c fails: shape mismatch due to slashes/dots).
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: .claude/skills/process-qa",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (path-shaped, fails shape gate), got: {stdout!r}")

    def test_allow_registry_unreadable_fail_open(self):
        """
        Simulate registry.json unavailable by patching the path via monkeypatching.
        Expected: ALLOW (fail-open: cannot validate -> do not block).
        """
        import importlib.util
        spec = importlib.util.spec_from_file_location("rtv", _HOOK)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)

        # Monkey-patch _registry_path to return a nonexistent path
        mod._registry_path = lambda: "/nonexistent/path/registry.json"

        # Redirect stdin/stdout
        old_stdin = sys.stdin
        old_stdout = sys.stdout
        sys.stdin = io.StringIO(json.dumps({
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: totally-ghost-agent",
            },
        }))
        captured = io.StringIO()
        sys.stdout = captured
        try:
            mod.main()
        finally:
            sys.stdin = old_stdin
            sys.stdout = old_stdout

        output = captured.getvalue()
        self.assertTrue(
            _is_allow(output),
            f"Expected ALLOW (fail-open when registry unreadable), got: {output!r}",
        )

    def test_allow_malformed_stdin(self):
        """
        Malformed/empty stdin payload.
        Expected: ALLOW, exit 0, no crash.
        """
        for bad_input in [b"", b"   ", b"not json at all", b"{broken"]:
            result = subprocess.run(
                [_PYTHON, _HOOK],
                input=bad_input,
                capture_output=True,
            )
            self.assertEqual(result.returncode, 0,
                             f"Hook must exit 0 for bad input: {bad_input!r}")
            self.assertFalse(result.stdout.strip(),
                             f"Hook must emit nothing for bad input: {bad_input!r}; got {result.stdout!r}")

    def test_allow_empty_new_string(self):
        """
        Edit with empty new_string: nothing to validate.
        Expected: ALLOW.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout), f"Expected ALLOW (empty new_string), got: {stdout!r}")

    def test_allow_multiedit_all_real_agents(self):
        """
        MultiEdit with two edits, both adding real agents to MUST DISPATCH lines.
        Expected: ALLOW.
        """
        payload = {
            "tool_name": "MultiEdit",
            "tool_input": {
                "file_path": _skill_path("process-qa"),
                "edits": [
                    {
                        "old_string": "OLD1",
                        "new_string": f"MUST DISPATCH: {_REAL_AGENT}",
                    },
                    {
                        "old_string": "OLD2",
                        "new_string": f"MUST DISPATCH: {_REAL_AGENT}",
                    },
                ],
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout), f"Expected ALLOW (MultiEdit real agents), got: {stdout!r}")

    def test_allow_deprecated_allowlist_name_in_dispatch_position(self):
        """
        An agent name added to DEPRECATED_ALLOWLIST passes through even in a dispatch position.
        This test patches DEPRECATED_ALLOWLIST in the module to verify the allowlist mechanism works.
        """
        import importlib.util
        spec = importlib.util.spec_from_file_location("rtv", _HOOK)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)

        # Temporarily patch DEPRECATED_ALLOWLIST with a ghost name
        original = mod.DEPRECATED_ALLOWLIST
        mod.DEPRECATED_ALLOWLIST = frozenset({"my-retired-agent"})

        old_stdin = sys.stdin
        old_stdout = sys.stdout
        sys.stdin = io.StringIO(json.dumps({
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: my-retired-agent",
            },
        }))
        captured = io.StringIO()
        sys.stdout = captured
        try:
            mod.main()
        finally:
            sys.stdin = old_stdin
            sys.stdout = old_stdout
            mod.DEPRECATED_ALLOWLIST = original

        output = captured.getvalue()
        self.assertTrue(
            _is_allow(output),
            f"Expected ALLOW (name in DEPRECATED_ALLOWLIST), got: {output!r}",
        )


class TestDenyProtocolShape(unittest.TestCase):
    """Verify the deny output has the exact hookSpecificOutput shape required by Claude Code."""

    def test_deny_output_protocol_shape(self):
        """
        Deny output must match exactly:
        {"hookSpecificOutput": {"hookEventName": "PreToolUse",
                                "permissionDecision": "deny",
                                "permissionDecisionReason": "..."}}
        Must NOT use the SubagentStop protocol {"decision": "block", ...}.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _skill_path("process-qa"),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: totally-ghost-agent-xyz",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(stdout.strip(), "Expected non-empty deny output")

        obj = json.loads(stdout.strip())
        self.assertIn("hookSpecificOutput", obj,
                      "Top-level key must be 'hookSpecificOutput'")
        hso = obj["hookSpecificOutput"]
        self.assertEqual(hso.get("hookEventName"), "PreToolUse")
        self.assertEqual(hso.get("permissionDecision"), "deny")
        self.assertIsInstance(hso.get("permissionDecisionReason"), str)
        self.assertTrue(hso["permissionDecisionReason"].strip())

        # Must NOT use the wrong protocol
        self.assertNotIn("decision", obj,
                         "Must NOT use {'decision':'block'} SubagentStop protocol at top level")

    def test_deny_names_ghost_in_reason(self):
        """
        Deny reason must name the specific unresolved token, not a generic message.
        """
        ghost = "utterly-fake-agent-2026"
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": f"MUST DISPATCH: {ghost}",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_deny(stdout))
        reason = json.loads(stdout)["hookSpecificOutput"]["permissionDecisionReason"]
        self.assertIn(ghost, reason,
                      f"Deny reason must name the unresolved token '{ghost}'")


class TestDispatchPhraseProseAllows(unittest.TestCase):
    """
    Regression suite locking the _DISPATCH_PHRASE_RE removal (FP fix).

    All prose forms of "dispatches to X" / "dispatch X" MUST ALLOW.
    The verb form is indistinguishable from ordinary English and was a
    systematic false-positive source: the detector was removed.
    Only MUST DISPATCH: lines, subagent_type: fields, and table rows are
    unambiguous dispatch positions.
    """

    def test_allow_prose_dispatches_to_sub_tasks(self):
        """
        'The system dispatches to sub-tasks based on type.' -> ALLOW.
        'sub-tasks' is agent-shaped but this is plain prose: must not block.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "The system dispatches to sub-tasks based on type.",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (prose dispatch phrase), got: {stdout!r}")

    def test_allow_prose_dispatch_rate_limited_requests(self):
        """
        'dispatch rate-limited requests to the queue.' -> ALLOW.
        'rate-limited' is agent-shaped but this is plain prose: must not block.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "dispatch rate-limited requests to the queue.",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (prose dispatch phrase), got: {stdout!r}")

    def test_allow_prose_hook_dispatches_to_agent_registry_check(self):
        """
        'The hook dispatches to agent-registry-check and returns.' -> ALLOW.
        This is prose: verb-dispatch must never block.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _claude_md_path(),
                "old_string": "OLD",
                "new_string": "The hook dispatches to agent-registry-check and returns.",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_allow(stdout),
                        f"Expected ALLOW (prose dispatch to hook name), got: {stdout!r}")

    def test_deny_must_dispatch_with_nonexistent_agent_still_works(self):
        """
        Confirm the legit MUST DISPATCH: syntactic path still DENIES after the
        _DISPATCH_PHRASE_RE removal.
        """
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _skill_path("process-qa"),
                "old_string": "OLD",
                "new_string": "MUST DISPATCH: process-qa, nonexistent-agent, pm",
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_deny(stdout),
                        f"Expected DENY (MUST DISPATCH: with ghost agent), got: {stdout!r}")
        self.assertIn("nonexistent-agent", _deny_names(stdout),
                      f"Deny reason must name 'nonexistent-agent'; got: {stdout!r}")

    def test_deny_subagent_type_ghost_still_works(self):
        """
        Confirm subagent_type: "ghost-reviewer" still DENIES after the
        _DISPATCH_PHRASE_RE removal.
        """
        content = (
            "---\n"
            "name: example-skill\n"
            "---\n"
            "\n"
            'subagent_type: "ghost-reviewer"\n'
        )
        payload = {
            "tool_name": "Write",
            "tool_input": {
                "file_path": _skill_path("example-skill"),
                "content": content,
            },
        }
        stdout, rc = _run_hook(payload)
        self.assertEqual(rc, 0)
        self.assertTrue(_is_deny(stdout),
                        f"Expected DENY (subagent_type ghost), got: {stdout!r}")
        self.assertIn("ghost-reviewer", _deny_names(stdout),
                      f"Deny reason must name 'ghost-reviewer'; got: {stdout!r}")


class TestExitCodeAlways0(unittest.TestCase):
    """Hook must always exit 0: it must never abort the session."""

    def test_exit_0_on_deny(self):
        payload = {
            "tool_name": "Write",
            "tool_input": {
                "file_path": _skill_path("x"),
                "content": "MUST DISPATCH: ghost-agent-zzzz",
            },
        }
        _, rc = _run_hook(payload)
        self.assertEqual(rc, 0)

    def test_exit_0_on_allow(self):
        payload = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": _non_routing_path(),
                "old_string": "x",
                "new_string": "y",
            },
        }
        _, rc = _run_hook(payload)
        self.assertEqual(rc, 0)

    def test_exit_0_on_empty_input(self):
        result = subprocess.run([_PYTHON, _HOOK], input=b"", capture_output=True)
        self.assertEqual(result.returncode, 0)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    unittest.main(verbosity=2)
