#!/usr/bin/env python3
"""Generate Home.md from every discovered project's STATE.md frontmatter + body.

Project discovery is delegated to `.claude/hooks/_project_discovery.py` (bounded
depth 2, a directory is a project iff it directly contains STATE.md), so nested
projects such as `Personal/Finance` and `Umbrella/Module-8B` are included and are
keyed on their full relative identity rather than a bare leaf name.

Reads each discovered `STATE.md`:
- Extracts frontmatter (status, last_action, milestone, updated)
- Extracts "## Next" section body (first 2-3 items)
- Sorts projects by STATE.md mtime (most recently modified first)
- Filters: active + waiting + building status only (excludes done/archived)
- Renders Home.md using a stable template

Header is rewritten honestly: "auto-generated by .claude/scripts/generate-home.py
on YYYY-MM-DD HH:MM: do not edit by hand."

Idempotent: re-runs produce same output unless STATE.md files changed.

Invocation:
- Manual: `python .claude/scripts/generate-home.py`
- Optional: wire to SessionStart hook for fresh Home.md per session

Per CLAUDE.md stewardship-creates-orphans rule: this script writes to vault root
Home.md which is referenced by Resources/KB/index.md + log.md + many docs: no
orphan risk.
"""
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed", file=sys.stderr)
    sys.exit(1)

VAULT = Path(__file__).resolve().parent.parent.parent
PROJECTS = VAULT / "Projects"
HOME = VAULT / "Home.md"

# Cross-directory import of the shared discovery helper, following the precedent
# in .claude/hooks/hook-write-regression-gate.py (which inserts the scripts dir).
sys.path.insert(0, str(VAULT / ".claude" / "hooks"))
from _project_discovery import discover_projects  # noqa: E402

# Projects to exclude from Home.md (closed / not user-facing).
# Matched against the FULL RELATIVE IDENTITY, not a leaf: `Vault-Maintenance`
# excludes only the top-level stewardship hub, and would NOT accidentally
# exclude a hypothetical `Something/Vault-Maintenance`.
EXCLUDE_NAMES = {"Vault-Maintenance"}

# Status values that mean "show in active section"
ACTIVE_STATUS = {"active", "building", "waiting", "in-progress"}


def split_fm(text: str):
    if not text.startswith("---"):
        return None, text
    rest = text[3:]
    end = rest.find("\n---")
    if end == -1:
        return None, text
    fm_text = rest[:end + 1]
    # +4 skips `\n---`; lstrip handles `\r\n` line endings on Windows
    body = rest[end + 4:].lstrip("\r\n")
    try:
        fm = yaml.safe_load(fm_text)
    except yaml.YAMLError:
        return None, body
    return fm, body


def extract_section(body: str, header: str, max_lines: int = 6) -> str:
    """Extract first N lines after `## {header}` heading."""
    pattern = rf"^##\s+{re.escape(header)}\s*\n"
    m = re.search(pattern, body, re.MULTILINE)
    if not m:
        return ""
    rest = body[m.end():]
    # Stop at next ## header
    next_h = re.search(r"^##\s+", rest, re.MULTILINE)
    section = rest[:next_h.start()] if next_h else rest
    lines = [l for l in section.strip().split("\n") if l.strip()]
    if max_lines and len(lines) > max_lines:
        lines = lines[:max_lines]
    return "\n".join(lines)


def truncate(s: str, n: int = 280) -> str:
    if not s:
        return ""
    s = str(s).strip().replace("\n", " ")
    s = re.sub(r"\s+", " ", s)
    if len(s) > n:
        return s[:n].rstrip() + "..."
    return s


def collect_projects():
    """Return list of (identity, state_path, fm, body, mtime) tuples for active projects.

    `identity` is the project's path relative to Projects/ with forward slashes
    (`Umbrella/Module-8B`), which is what render_project_block turns into links.
    """
    out = []
    for name, state_path, _plan_path in discover_projects(PROJECTS):
        state_md = Path(state_path)
        if name in EXCLUDE_NAMES:
            continue
        try:
            text = state_md.read_text(encoding="utf-8")
        except Exception:
            continue
        fm, body = split_fm(text)
        if not isinstance(fm, dict):
            print(f"WARN: {state_md}: frontmatter not a dict ({type(fm).__name__}), skipping", file=sys.stderr)
            continue
        status = str(fm.get("status", "")).lower().strip().lstrip("#")
        if status not in ACTIVE_STATUS:
            continue
        mtime = state_md.stat().st_mtime
        out.append((name, state_md, fm, body, mtime))
    out.sort(key=lambda t: t[4], reverse=True)
    return out


def render_project_block(name: str, fm: dict, body: str, is_focus: bool) -> str:
    state_rel = f"Projects/{name}/STATE.md"
    plan_rel = f"Projects/{name}/task_plan.md"
    work_rel = f"Projects/{name}/work"
    status = str(fm.get("status", "active")).strip().lstrip("#")
    milestone = truncate(fm.get("milestone", ""), 140)
    last_action = truncate(fm.get("last_action", ""), 360)
    next_section = extract_section(body, "Next", max_lines=5)
    next_text = ""
    if next_section:
        # Compress to inline bullets
        next_lines = [l.lstrip("-* 0123456789.").strip() for l in next_section.split("\n") if l.strip()]
        next_lines = [l for l in next_lines if l]
        if next_lines:
            next_text = "; ".join(truncate(l, 200) for l in next_lines[:3])
    focus_marker = ": **focus**" if is_focus else ""
    lines = [
        f"### {name}{focus_marker}: {status}",
        f"- **Last:** {last_action}" if last_action else "",
        f"- **Milestone:** {milestone}" if milestone else "",
        f"- **Next:** {next_text}" if next_text else "",
        f"- **Files:** [[{state_rel}|state]] · [[{plan_rel}|tasks]] · [[{work_rel}|work files]]",
        "",
    ]
    return "\n".join(l for l in lines if l != "")


def render_home(projects, generated_at: datetime) -> str:
    focus = projects[0][0] if projects else "(none)"
    # Anchor date to max mtime of input STATE.md files for idempotency.
    # Re-runs on unchanged inputs produce byte-identical output.
    if projects:
        anchor = datetime.fromtimestamp(max(p[4] for p in projects))
    else:
        anchor = generated_at
    parts = [
        "---",
        f"date: {anchor.strftime('%Y-%m-%d')}",
        "tags: [home, navigation, vault]",
        "status: active",
        "---",
        "# Vault: Home",
        "",
        f"> Auto-generated by `.claude/scripts/generate-home.py` from STATE.md files dated {anchor.strftime('%Y-%m-%d')}. Do not edit by hand.",
        f"> Active focus: **{focus}** (STATE.md modified most recently).",
        "",
        "---",
        "",
        "## Active Projects",
        "",
    ]
    for i, (name, _, fm, body, _) in enumerate(projects):
        parts.append(render_project_block(name, fm, body, is_focus=(i == 0)))
        parts.append("---")
        parts.append("")
    parts.extend([
        "## Vault Navigation",
        "",
        "- **Inbox**: dump zone ([Inbox/](Inbox/))",
        "- **Daily Notes**: auto-generated daily logs ([Daily Notes/](Daily%20Notes/))",
        "- **Resources**: reference material and KB ([Resources/](Resources/))",
        "- **Templates**: note templates ([Templates/](Templates/))",
        "- **Archives**: closed projects ([Archives/](Archives/))",
        "- **MOCs**: topical hubs ([Resources/KB/](Resources/KB/))",
        "- **Memory**: Claude's persistent facts at `~/.claude/projects/C--Users-exampleuser-Desktop-Vault/memory/MEMORY.md`",
        "",
        "---",
        "",
        "## How this file works",
        "",
        "- Auto-generated from every discovered `STATE.md` under `Projects/`, found by "
        "`.claude/hooks/_project_discovery.py`: a directory is a project iff it directly "
        "contains `STATE.md`, searched to depth 2, keyed on its full relative identity "
        "(for example `Personal/Finance`).",
        "- Projects sorted by most-recently-modified STATE.md (top = most active).",
        "- Excludes: `Vault-Maintenance` (internal stewardship hub); projects with status `done` or `archived`.",
        "- Regenerate: `python .claude/scripts/generate-home.py`.",
        "",
    ])
    return "\n".join(parts)


def main():
    projects = collect_projects()
    if not projects:
        print("WARN: No active projects found", file=sys.stderr)
    generated_at = datetime.now()
    content = render_home(projects, generated_at)
    HOME.write_text(content, encoding="utf-8")
    print(f"Home.md regenerated ({len(projects)} active project(s)). Focus: {projects[0][0] if projects else '(none)'}")


if __name__ == "__main__":
    main()
